# Generated by Django 3.1.3 on 2020-11-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naamvinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deelnemers', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
