# Generated by Django 3.1.3 on 2020-11-09 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naamvinder', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='selfDestroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='deelnemers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=7),
        ),
    ]
