# Generated by Django 3.1.3 on 2020-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naamvinder', '0005_auto_20201109_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='destinationEmail',
            field=models.CharField(default='', max_length=128),
        ),
    ]
